# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqltzEBsd2kDUob05xuugnNEPo-5odO4
"""



# 1. ATM PIN Verification

# Your cousin works at a bank and is testing a simple ATM simulator. A user gets up to 3 attempts to enter the correct PIN. After each wrong attempt, the program should print how many tries are left. If they run out of attempts, the card gets locked.

# Given a correct_pin and a list entered_pins (the attempts in order), write a program that loops through the attempts (max 3), checks each one against correct_pin, and prints "Access Granted" if it matches, otherwise "Wrong PIN, X tries left". If all 3 attempts fail, print "Card Locked".

# For Loop
correct_pin = 5678
entered_pins = [1111, 2222, 1234]

max_attempts = 3
access = False

for i in range(min(3, len(entered_pins))):
    if entered_pins[i] == correct_pin:
        print("Access Granted")
        access = True
        break
    else:
        print(f"Wrong PIN, {2-i} tries left")

if not access:
    print("Card Locked")

# While Loop
correct_pin = 1234
entered_pins = [1111, 2222, 1234]

i = 0
access = False

while i < 3 and i < len(entered_pins):
    if entered_pins[i] == correct_pin:
        print("Access Granted")
        access = True
        break
    else:
        print(f"Wrong PIN, {2-i} tries left")
    i += 1

if not access:
    print("Card Locked")

# 2. Grocery Checkout Total

# Your mom asked you to build a quick checkout tool for her small shop. Items are entered one at a time and added to a running total. If the total crosses ₹1000 at any point, a 10% discount should automatically apply to the rest of the checkout.

# Given a list item_prices, write a program that loops through the prices, adding each to a running total. Once the total crosses ₹1000, apply a 10% discount to all further items added. Print the final total.

# For Loop
item_prices = [400, 350, 300, 200]

total = 0
discount = False

for price in item_prices:
    if discount:
        total += price * 0.9
    else:
        total += price
        if total > 1000:
            discount = True

print("Final Total =", total)

# While Loop
item_prices = [400, 350, 300, 200]

total = 0
discount = False
i = 0

while i < len(item_prices):
    if discount:
        total += item_prices[i] * 0.9
    else:
        total += item_prices[i]
        if total > 1000:
            discount = True
    i += 1

print("Final Total =", total)

# 3. Number Guessing Game

# Your little brother wants a guessing game where the computer picks a number and he keeps guessing until he gets it right. After each guess, the program should print "Too High", "Too Low", or "Correct".

# Given a secret_number and a list guesses (in the order they were made), write a program that loops through the guesses, printing "Too High" or "Too Low" for each using if-else, and stops as soon as it finds the correct guess, printing "Correct" along with how many guesses it took.

# For Loop
secret_number = 25
guesses = [10, 30, 20, 25]

for i in range(len(guesses)):
    if guesses[i] > secret_number:
        print("Too High")
    elif guesses[i] < secret_number:
        print("Too Low")
    else:
        print("Correct")
        print("Guesses =", i + 1)
        break

# While Loop
secret_number = 20
guesses = [10, 30, 20, 25]

i = 0

while i < len(guesses):
    if guesses[i] > secret_number:
        print("Too High")
    elif guesses[i] < secret_number:
        print("Too Low")
    else:
        print("Correct")
        print("Guesses =", i + 1)
        break
    i += 1

# 4. Movie Ticket Booking

# You're helping at a local cinema's booking counter. Tickets are sold one at a time until either all seats are sold or someone tries to book more seats than are available (in which case that request is rejected and booking stops).

# Given total_seats and a list booking_requests (seats requested per booking, in order), write a program that loops through the requests, reducing the available seats each time. If a request asks for more seats than are available, print "Not enough seats" and stop the loop. Print the number of seats remaining at the end.

# For Loop
total_seats = 20
booking_requests = [4, 6, 5, 8]

available = total_seats

for seats in booking_requests:
    if seats > available:
        print("Not enough seats")
        break
    else:
        available -= seats

print("Seats remaining =", available)

# While Loop
total_seats = 20
booking_requests = [4, 6, 5, 8]

available = total_seats
i = 0

while i < len(booking_requests):
    if booking_requests[i] > available:
        print("Not enough seats")
        break
    else:
        available -= booking_requests[i]
    i += 1

print("Seats remaining =", available)

# 5. Study Streak Tracker

# You're building a habit tracker for your study group. Each day's quiz score is checked one at a time. The streak continues as long as the score is 60 or above; the moment a score drops below 60, the streak breaks and processing stops.

# Given a list scores (daily quiz scores in order), write a program that loops through the scores, using if-else to check each one: if it's 60 or above, increase the streak count; if it drops below 60, print "Streak broken" and stop the loop. Print the final streak length.

# For Loop
scores = [75, 82, 60, 59, 90]

streak = 0

for score in scores:
    if score >= 60:
        streak += 1
    else:
        print("Streak broken")
        break

print("Final streak =", streak)

# While Loop
scores = [75, 82, 60, 59, 90]

streak = 0
i = 0

while i < len(scores):
    if scores[i] >= 60:
        streak += 1
    else:
        print("Streak broken")
        break
    i += 1

print("Final streak =", streak)

